# Project information
site_name: 'IoTaaP Tutorials'
site_description: 'IoTaaP Tutorials'
repo_url: 'https://github.com/iotaap/tutorials'
nav:
  - Home: index.md
  - Working Environment: working-environment.md
  - IoTaaP - Pins: iotaap-pins.md
  - IoTaaP - Jumpers: iotaap-jumpers.md
  - IoTaaP - Blinky LED: iotaap-blinkyled.md
  - IoTaaP - MISC: iotaap-misc.md
  - IoTaaP - OLED: iotaap-oled.md
  - IoTaaP - Serial: iotaap-serial.md
  - IoTaaP - ADC: iotaap-adc.md
  - IoTaaP - DAC: iotaap-dac.md
  - IoTaaP - PWM: iotaap-pwm.md
  - IoTaaP - Hall: iotaap-hall.md
  - IoTaaP - Buzzer: iotaap-buzzer.md
  - IoTaaP - WiFi: iotaap-wifi.md
  - MQTT Setup: mqtt-setup.md
  - IoTaaP - MQTT: iotaap-mqtt.md
  - IoTaaP - TCP Client: iotaap-tcpclient.md
  - IoTaaP - TCP Server: iotaap-tcpserver.md
  - IoTaaP - TSL2561: iotaap-tsl2561.md
  - IoTaaP - Grafana: iotaap-grafana.md
  - IoTaaP - MQTTS: iotaap-mqtts.md
  - IoTaaP - API: iotaap-api.md
  - WS2812 LED Module: ws2812-module.md
  - Weather Module: weather-module.md
        
# Copyright
copyright: 'Copyright IoTaaP'

theme: 
    name: material
    palette:
        primary: 'light-blue'
        accent: 'deep-purple'
#    font:
#        text: 'Ubuntu'
#        code: 'Ubuntu Mono'
    logo: 'images/logo.png'
    favicon: 'images/favicon.png'
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  social:
    - type: 'github'
      link: 'https://github.com/iotaap'
    - type: 'twitter'
      link: 'https://twitter.com/iotaap'
    - type: 'facebook'
      link: 'https://www.facebook.com/iotaap'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCC9hU3ndh6bh-LbW3YjI98g'