# Project information
site_name: 'IoTaaP Tutorials'
site_description: 'IoTaaP Tutorials'
repo_url: 'https://github.com/iotaap/tutorials'
nav:
  - Home: index.md
  - Working Environment: working-environment.md
  - IoTaaP - Pins: iotaap-pins.md
  - IoTaaP - Jumpers: iotaap-jumpers.md
  - IoTaaP - Blinky LED: iotaap-blinkyled.md
  - IoTaaP - MISC: iotaap-misc.md
  - IoTaaP - OLED: iotaap-oled.md
  - IoTaaP - Serial: iotaap-serial.md
  - IoTaaP - ADC: iotaap-adc.md
  - IoTaaP - DAC: iotaap-dac.md
  - IoTaaP - PWM: iotaap-pwm.md
  - IoTaaP - Hall: iotaap-hall.md
  - IoTaaP - Buzzer: iotaap-buzzer.md
  - IoTaaP - WiFi: iotaap-wifi.md
  - MQTT Setup: mqtt-setup.md
  - IoTaaP - MQTT: iotaap-mqtt.md
  - IoTaaP - TCP Client: iotaap-tcpclient.md
  - IoTaaP - TCP Server: iotaap-tcpserver.md
  - IoTaaP - TSL2561: iotaap-tsl2561.md
  - IoTaaP - Grafana: iotaap-grafana.md
  - IoTaaP - MQTTS: iotaap-mqtts.md
  - WS2812 LED Module: ws2812-module.md
  - Weather Module: weather-module.md
  - CAN Module: can-module.md
  - Servo Motor Module: servo-motor-module.md
        
copyright: 'Copyright &copy; IoTaaP'

theme: 
    name: material
    palette:
        primary: 'light-blue'
        accent: 'deep-purple'
    logo: 'images/logo.png'
    favicon: 'images/favicon.png'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iotaap
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iotaap
      name: Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/iotaap
      name: Facebook
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCC9hU3ndh6bh-LbW3YjI98g
      name: YouTube